#!/bin/bash

patch-package

if [ -z "$CI" ]; then

  E2E=true npm run test -- -b

else

  npm run fork:start -- -q
  sleep 10

  E2E=true npm run test -- -b
  RESULT=$?

  npm run fork:stop

  exit $RESULT

fi
